### PR TITLE
Fixes #132 The symlink following logic in src() was incorrect resulting in wrong file.base being generated.

### LINKED ISSUE #132: Symlink following logic in src() seems wrong to me
Basically, the generated vinyl file base should be what's set to to the symlink itself:

Say the src directory structure is like:
```
|-- foo
    |-- bar -> baz
    |-- baz
        |-- qux.txt
```
the symlink should produce: ./target/foo/bar at the end with qux.txt in it if dest is set to target. In practice it doesn't.

The reason is the file base should always be set to ./foo for anything linked by bar whereas the original recursive logic would produce foo/baz.

Such incorrect logic would yield a flattened file structure and empty directories at the end:

```
pipe(gulp.dest('target'))

the original logic would generate:

|-- target
    |-- foo
    |-- baz (empty)
    |-- qux.txt

whereas the fixed logic generates:

|-- target
    |-- foo
        |-- bar
            |-- qux.txt
```

I've opened a PR here: https://github.com/gulpjs/vinyl-fs/pull/131
Please check it out.

### PR DESCRIPTION
**Pull request by xunnanxu**
Basically, the generated vinyl file base should be what's set to to the symlink itself:

foo/bar -> baz/qux.txt
this should produce: foo/baz/qux.txt

but the file base should still default to ./foo whereas the original recursive logic would produce foo/baz.

Such incorrect logic would yield a flattened file structure and empty directories at the end.

### CODE REVIEW

File: test/src.js [hunk 1]
```diff
@@ -385,22 +385,35 @@ describe('source stream', function() {
...
+    var expectedPath = path.join(__dirname, linkTarget);
 
-    var stream = vfs.src('./fixtures/test-symlink-dir', {cwd: __dirname});
-    stream.on('data', function(file){
+    var stream = vfs.src(linkTarget, {cwd: __dirname, base: __dirname});
+    stream.on('data', function(file) {
+      file.base.should.equal(__dirname);
+      // the path should be the symlink itself
       file.path.should.equal(expectedPath);
+      // but the stats should have be updated
```
Comment (justinsa) [inline test/src.js]: "but the stats should be updated", you have an extraneous "have" in there.

**Comment by phated** [comment]
@xunnanxu I just had a striking realization that this might be the exact same thing as https://github.com/gulpjs/gulp/issues/1427

I just ran your branch against the case outlined in that issue and it seems to have fixed it.  Do you have a chance to rebase this onto master?

**Comment by phated** [comment]
It seems that this would solve the linked issue but doesn't actually create the symlinks that exist in the original source; instead, it writes the files with the contents of the symlinked files. There is still another problem related to `{ followSymlinks: false }` but this fixes the default case of `{ followSymlinks: true }`

**Comment by phated** [comment]
Is there a cleaner way to implement this?  Mutation passing across stream boundaries seems really messy to me.

**Comment by GregDracoulis** [comment]
@phated what is your concern there? setting `symlinkTarget` and `path`, then using `symlinkTarget` to change `path` back?

I almost feel like the logic in `resolveSymlinks` should be worked into `createFile` instead of having to pass that mutation in. After all, it's only used that one place.

**Comment by phated** [comment]
@GregDracoulis yeah, I wonder if it could be handled in a different way in vinyl-fs or maybe even in vinyl proper?  I could see resolveSymlinks possiblt being inlined, too

**Comment by xunnanxu** [comment]
@phated Sorry I was out of town for a while and just got back recently. I'll try to rebase master and see if I can make it better when I have a chance

**Comment by xunnanxu** [comment]
@phated I rebased master and it seems AppVeyor doesn't like the test while travis works fine and so is my local env. Can you confirm if it's configured properly? How is that different from travis and why do we need that?

**Comment by xunnanxu** [comment]
@phated 
"It seems that this would solve the linked issue but doesn't actually create the symlinks that exist in the original source; instead, it writes the files with the contents of the symlinked files. There is still another problem related to { followSymlinks: false } but this fixes the default case of { followSymlinks: true }"

followSymlinks: false will work as it simply wraps the symlink itself and that behavior is already covered by tests (below the ones I added).

**Comment by phated** [comment]
@xunnanxu correct but our logic attempts to traverse a symlink'ed directory and explodes.  I think it is a separate issue than this.

Appveyor is CI for windows.  Symlinks don't really work on windows, so try to get it working there but if it isn't possible, just add a skip if running on windows (see some of the chmod/utimes tests).

**Comment by xunnanxu** [comment]
@phated is there an issue related to what you said? I'm not sure if I really understand what the other problem is. We may need to open another PR to address that one.

**Comment by phated** [comment]
@xunnanxu no issue, just something I stumbled upon while poking around with your original issue, this PR and the linked gulp issue.  I'll create an in-depth issue (with failing test) once we get this PR sorted out.

**Comment by xunnanxu** [comment]
@phated nailed. Please continue reviewing when you have a chance.

File: lib/src/wrapWithVinylFile.js [hunk 2]
```diff
@@ -24,11 +35,10 @@ function resolveSymlinks(options) {
           return cb(err);
         }
 
-        globFile.base = path.dirname(filePath);
         globFile.path = filePath;
 
         // Recurse to get real file stat
-        resolveFile(globFile, enc, cb);
+        return resolveFile(globFile, enc, cb);
```
Comment (phated) [inline lib/src/wrapWithVinylFile.js]: no reason for return

File: lib/src/wrapWithVinylFile.js [hunk 3]
```diff
@@ -16,7 +16,18 @@ function resolveSymlinks(options) {
...
+        if (globFile.symlinkTarget) {
+          // If we reach here, it means there is at least one
+          // symlink on the path and we need to rewrite the path
+          // to its original value.
+          // Updated file stats will tell getContents() to actually read it.
+          vinylFile.path = globFile.symlinkTarget;
+        }
+        return cb(null, vinylFile);
+      }
+      if (!globFile.symlinkTarget) {
```
Comment (phated) [inline lib/src/wrapWithVinylFile.js]: I think this should be inside the `fs.realpath` callback before we modify the `globFile.path`

**Comment by phated** [comment]
@xunnanxu looking pretty good, I just had a couple of comments on things I'd like changed.

File: lib/src/wrapWithVinylFile.js (hunk 3 above)
Comment (phated) [inline lib/src/wrapWithVinylFile.js]: I understand but I still think it doesn't need to happen if the realpath errors

**Comment by phated** [comment]
Merged + squashed with the new github feature.  I also added a commit moving the `originalSymlinkPath` assignment inside the `realpath` callback and tests still pass.

**Comment by phated** [comment]
Published as 2.4.3 - many thanks to @xunnanxu
